In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor

### creating regression using make_regression ###

In [2]:
x,y = make_regression(n_samples=100, n_features=4,n_informative=1, n_targets=1, noise=20, random_state = 13)

In [3]:
x.shape

(100, 4)

In [4]:
y.shape

(100,)

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [6]:
x_train.shape

(80, 4)

### creating our own mini batch gradient descent ###

In [7]:
import random
class miniGD:
    def __init__(self,learning_rate,epochs,batch_size):
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        self.intercept_ = None
        self.coef_ = None

    def fit(self,x_train,y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])

        for i in range(self.epochs):
            for j in range(int(x_train.shape[0]/self.batch_size)):
                idx = random.sample(range(x_train.shape[0]), self.batch_size)
                y_hat = np.dot(x_train[idx],self.coef_)+self.intercept_
                intercept_derivate = -1*np.mean(y_train[idx]-y_hat)
                coef_derivate = -1 * np.dot(x_train[idx].T, (y_train[idx] - y_hat))
                self.intercept_ = self.intercept_ - (self.lr*intercept_derivate)
                self.coef_ = self.coef_ - (self.lr*coef_derivate)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

### using sklearn's mini batch gradient descent ###

In [8]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [9]:
batch_size = 35

for i in range(10000):
    
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [10]:
mgd = miniGD(0.01,10000,35)

In [11]:
mgd.fit(x_train,y_train)

In [12]:
sgd.intercept_

array([-5.8668706])

In [13]:
sgd.coef_

array([94.45442295, -5.91097006,  1.4828074 ,  0.43955902])

In [14]:
mgd.intercept_

np.float64(2.6406717283018586)

In [15]:
mgd.coef_

array([96.20047036, -0.58220202,  0.10536544, -1.54143344])

## as you can see the values of intercept and coeficients are pretty close ##