In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn.datasets import make_regression

### creating regression model having 4 features ###

In [2]:
x,y = make_regression(n_samples=100, n_features=4, n_informative=1, n_targets=1,noise=20,random_state=13)

In [3]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

### using our own SGD class regressor class ###

In [4]:
class SGD:
    def __init__(self,learning_rate,epochs):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self,x_train,y_train):
        self.coef_ = np.ones(x_train.shape[1])
        self.intercept_ = 0

        for i in range(self.epochs):
            for j in range(x_train.shape[0]):
                idx = np.random.randint(0,x_train.shape[0])
                y_hat = np.dot(x_train[idx],self.coef_)+self.intercept_
                intercept_der = -1*(y_train[idx]-y_hat)
                coef_der = -1*np.dot(x_train[idx].T,(y_train[idx]-y_hat))

                self.intercept_ = self.intercept_-(self.lr*intercept_der)
                self.coef_ = self.coef_ -(self.lr*coef_der)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_
            
        

### using sklearn's SGD regressor ###

In [5]:
sgd = SGDRegressor(max_iter = 100000,tol=None, random_state=42, eta0=0.01, learning_rate='constant', penalty=None, shuffle=False)

In [6]:
sgd.fit(x_train,y_train)

SGDRegressor(learning_rate='constant', max_iter=100000, penalty=None,
             random_state=42, shuffle=False, tol=None)

In [7]:
sgd2 = SGD(0.01,100000)

In [8]:
sgd2.fit(x_train,y_train)

### getting the value of intercept using both the classes to compare the workings ###

In [10]:
sgd.intercept_

array([2.50399853])

In [11]:
sgd.coef_

array([95.72048838, -1.67577697, -0.48810396, -0.85437836])

In [12]:
sgd2.intercept_

np.float64(3.1835873106799513)

In [13]:
sgd2.coef_

array([96.30759424, -0.69321573, -1.38379388, -1.05402946])

## as you can see the values of intercept and coefficients are pretty close ##